
url: "https://eaton-lab.org" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/hack-the-planet" # the subpath of your site, e.g. /blog
title: "EEEB G4050" # the name of your site, e.g. ACME Corp.

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 0
